/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "Improvement:": "改进：",
    "New Features:": "新功能：",
    "Options": "选项",
    "Patch Notes": "更新日志",
    "Upgrades": "升级",
    "You can no longer place locked components^2.": "您不能再放置锁定的组件^2。",
    "Experimental Upgrades": "实验性升级",
    "Experiments": "实验",
    "Export save": "导出存档",
    "Faster repaint time by layering frequently updated ui (Improve fps/lag)": "通过对频繁更新的 ui 进行分层来加快重绘时间（提高 fps/lag）",
    "Faster tick timing (faster loading after offline)": "更快的滴答时间（离线后加载更快）",
    "Features:": "特征：",
    "Fixed an issue with game loop firing too often": "修复了游戏循环触发过于频繁的问题",
    "Fixed sell costs for some components": "某些组件的固定出售成本",
    "Fixed support for larger touch devices to allow for selling, etc": "修复了对更大触摸设备的支持以允许出售等",
    "Fixes extreme plating adding to max power despite not being bought yet": "尽管尚未购买，但修复了极端电镀以增加最大功率",
    "Fixes Heat Control Operator adding heat": "修复了热量控制操作员添加热量的问题",
    "Fixes heat outlet heat distribution bug with multi-tier setup": "修复了多层设置的热出口热量分布错误",
    "Fixes reflector ui load bug": "修复反射器 ui 加载错误",
    "Greatly improve performance": "大大提高性能",
    "Heat": "热量",
    "Heavily optimized the protium code that I ruined.": "对我破坏的 protium 代码进行了大量优化。",
    "Help": "帮助",
    "Hold keys in bracket and click to use the macro": "按住括号中的键并单击以使用宏",
    "Implemented Chlorophymium.": "实施了绿藻。",
    "Import save": "进口锯",
    "Changes": "变化",
    "Changes:": "变化：",
    "Checkered fill (ctrl+alt+shift)": "方格填充（ctrl+alt+shift）",
    "Click to Select": "点击选择",
    "Click to Upgrade": "点击升级",
    "Column (alt)": "列（alt）",
    "Components": "组件",
    "Coolant Innovation.": "冷却液创新。",
    "Current": "当前的",
    "Disable Auto Buy": "禁用自动购买",
    "Disable Auto Sell": "禁用自动出售",
    "Disable Heat Controller": "禁用热控制器",
    "Disable Offline Tick": "禁用离线Tick",
    "Disable Speed Hack": "禁用 Speed Hack",
    "Don't filter by part (shift)": "不要按零件过滤（shift）",
    "Download save": "下载保存",
    "Enable Google Drive Online Save": "启用 谷歌在线云盘 保存",
    "Enable Heat Controller": "启用热控制器",
    "Enable Local Save Only": "仅启用本地保存",
    "Enable Speed Hack": "启用速度破解",
    "Cancel": "取消",
    "A modification of": "修改",
    "A reset button!": "一个重置按钮！",
    "About": "关于",
    "Added individual experimental Particle Accelerator upgrades": "添加了单个实验性粒子加速器升级",
    "Added mitochdonrium.": "添加了线粒体。",
    "Added Objectives": "添加的目标",
    "Added patch notes": "添加了补丁说明",
    "Additional hotkeys/macro:": "其他热键/宏：",
    "Additions:": "补充：",
    "All accelerators no hold a max of 100 heat to prevent abuse of higher tiers.": "所有加速器都不能容纳最多 100 个热量，以防止滥用更高等级。",
    "Approximate EP per tick display.": "每个刻度显示的近似 EP。",
    "Back to Reactor": "回到反应堆",
    "Bang For Your Buck.": "全力以赴。",
    "Based on": "基于",
    "Basic Overview": "基本概述",
    "Buch": "布赫",
    "Bug fixes:": "Bug修复：",
    "Bug Fixes:": "Bug修复：",
    "Vent and Plating boosts for components multiply together instead of adding.": "排气和电镀促进组件相乘而不是相加。",
    "The game is immediately paused on loading or importing.": "游戏在加载或导入时立即暂停。",
    "Tick catchup": "Tick catchup",
    "Tile queue now buys as many as possible per tick": "瓷砖队列现在每次购买尽可能多",
    "UI based on": "用户界面基于",
    "Unpause": "取消暂停",
    "Upgrade tick catchup to offline ticks!": "将 tick catchup 升级为 离线tick！",
    "Usage": "用法",
    "Increase utility prices.": "提高公用事业价格。",
    "last tick)": "持续 tick）",
    "Left+right click triggering double click function and deleting tiles": "左键+右键触发双击功能并删除图块",
    "Less cpu usage when not on reactor tile panel": "不在反应器瓷砖面板上时减少 cpu 使用率",
    "Less lag spike for UI, tooltip": "UI、工具提示的层数减少",
    "Made help helpful.": "使帮助有所帮助。",
    "Make sure background get updated when placing plating so it doesn't get stuck on red": "确保在放置电镀时背景得到更新，这样它就不会卡在红色上",
    "Many upgrades now have a second tier.": "许多升级现在都有第二层。",
    "Moved the Coolant Innovation upgrade.": "移动冷却液创新升级。",
    "Multiple Exotic Particles gained when over 100% chance": "超过 100% 的几率获得多个奇异粒子",
    "New upgrade which prevents outlets from outputting more than what the vent can handle": "新升级可防止出口的输出超过通风口的处理能力",
    "Objective": "目标",
    "Offline Tick": "离线Tick",
    "Particle accelerators now have a standard upgrade.": "粒子加速器现在有一个标准升级。",
    "Parts": "零件",
    "Pause": "暂停",
    "per tick)": "每tick）",
    "Percentage bar and overheating redness are now updated in steps (reduce repainting)": "百分比条和过热发红现在分步更新（减少重绘）",
    "Place your first component in the reactor": "将您的第一个组件放入反应器中",
    "Platings (and possibly other things) now give 100% of their cost back when sold": "镀层（可能还有其他东西）现在在售出时返还 100% 的成本",
    "Power": "电力",
    "Reactor": "反应堆",
    "Reactor Incremental": "反应堆增量",
    "Reactor Knockoff": "反应堆仿制品",
    "Reactor meltdowns no longer instantly save the game.": "反应堆熔毁不再立即拯救游戏。",
    "Reboot and refund": "重启和退款",
    "Reboot for": "重新启动",
    "Reflectors now start with a base % greater than 0": "反射器现在以大于 0 的基本百分比开始",
    "Removed old Particle Accelerator upgrades": "移除旧的粒子加速器升级",
    "Reorganized upgrades.": "重组升级。",
    "Replaced every texture with similar ones of my own.": "用我自己的类似纹理替换了每个纹理。",
    "Replacing now works with same category parts, eg: downgrading, switching cell type": "替换现在适用于相同类别的部件，例如：降级、切换单元类型",
    "Replacing tiles is now faster": "更换瓷砖现在更快",
    "Replacing tiles with another now reimburse the amount for the part": "现在用另一个替换瓷砖可以补偿该部分的金额",
    "Reset game": "重置游戏",
    "Retexture:": "重新构造：",
    "Right click no longer buy stuff": "右键不再买东西",
    "Row (ctrl)": "行 (ctrl)",
    "Save data exporting and importing": "保存数据导出和导入",
    "Save game": "保存游戏",
    "Sci-fi User Interface Elements": "科幻用户界面元素",
    "See Patch Notes": "查看补丁说明",
    "Sell": "出售",
    "Shift/Double click now works on empty tiles": "Shift/双击现在适用于空瓷砖",
    "Signific code changes that shouldn't (but may) affect gameplay": "不应（但可能）影响游戏玩法的重大代码更改",
    "Spacing options (number)": "间距选项（数量）",
    "Speed Hack": "极速破解",
    "Speed hack toggle, throw more stuff into their own layer and thus reduce paint time (at the cost of memory)": "Speed hack切换，将更多的东西扔到自己的图层中，从而减少绘制时间（以内存为代价）",
    "Stats": "状态",
    "Styling fixes to \"pages\"": "对“页面”的样式修复",
    "% of max)\n\t\t": "% 最大)\n\t\t",
    "Dual Uranium Cell": "双铀电池",
    "Enable Auto Buy": "启用自动购买",
    "Enable Auto Sell": "启用自动出售",
    "Sell all your power by clicking \"Sell\"": "通过点击“出售”出售你所有的电力",
    "Uranium Cell": "铀电池",
    "% per tick (": "% 每 tick (",
    "), Improved Heatsinks level (S), Active Venting level (A)\n\t\t\t\t\t\t\tVentillation:\tV * (1 + A * C": "), 改进的散热器级别 (S), 主动通风级别 (A)\n\t\t\t\t\t\t\t通风：\tV * (1 + A * C",
    "), Sum of all plating tiers (P": "), 所有电镀层的总和 (P",
    "), Reinforced Heat Exchnagers level (R), Active Exchnagers level (A)\n\t\t\t\t\t\t\tTransfer Rate:\tT * (1 + A * C": "), 强化换热器等级 (R), 主动换热器等级 (A)\n\t\t\t\t\t\t\t 传输率：\tT * (1 + A * C",
    "/ 200)\n\t\t\t\t\t\t\tHeat Capacity:\tC * (1 + A * C": "/ 200)\n\t\t\t\t\t\t\t热容量：\tC * (1 + A * C",
    "Capacitors increase the total energy capacity of the reactor.\n\n\t\t": "电容器增加了反应堆的总能量容量。\n\n\t\t",
    "EP chance:": "EP几率：",
    "Sells for:": "出售：",
    "Power:": "电力：",
    "Heat:": "热量：",
    "Produces 1 power and 1 heat per tick. Lasts for 25 ticks.": "每 tick 产生 1 电力和 1 热量。 持续 25 tick。",
    "Power cells generate heat and power. Each cell in a given tile gives a pulse to each adjacent tile. Heat and power scale with the number of pulses recieved.\n\t\t\t\t\t\t\tPulses Recieved (U), Single cell base power (P), Single cell base heat (H), Cell count (C)\n\t\t\t\t\t\t\t(M) 1 for single, 4 for double, 12 for quad\n\t\t\t\t\t\t\tPower: P * (M + U)\n\t\t\t\t\t\t\tHeat: H * (M + U)^2/C\n\n\t\t": "电池产生热量和电能。 给定瓦片中的每个单元都被给予每个相邻瓦片的脉冲。 热量和功率随接收到的脉冲数量而变化。\n\t\t\t\t\t\t\t 接收到的脉冲 (U)、单电池基础功率 (P)、单电池基础热量 (H)、电池计数(C)\n\t\t\t\t\t\t\t(M) 1为单人，4人为双人，12人为四人\n\t\t\t\t\t\t\t功率： P * (M + U)\n\t\t\t\t\t\t\t热量：H * (M + U)^2/C\n\n\t\t",
    "Vents dissipate contained heat.\n\t\t\t\t\t\t\tBase heat capacity (C), Base ventillation (V), Sum of all capacitor tiers (C": "通风口散发热量。\n\t\t\t\t\t\t\t 基本热容量 (C)、基本通风量 (V)、所有电容器层的总和 (C",
    "platings increase the total heat capacity of the reactor.\n\n\t\t": "镀层增加了反应器的总热容量。\n\n\t\t",
    "Particle Accelerators produce exotic particles based on the heat passing through them each tick.\n\t\t\t\t\t\t\tMax Heat BEFORE upgrades (m), Max Heat (M), Heat throughput (H), Tier (T), Enhanced Acceleration Levle (E)\n\t\t\t\t\t\t\tParticle production: (Ln(min(M, H)) / 10 ^ (5-T)) * (min(M, H) / m) * 10^E\n\t\t": "粒子加速器根据每tick通过它们的热量产生奇异粒子。\n\t\t\t\t\t\t\t升级前的最大热量 (m), 最大热量 (M), 热通量 (H),等级 (T)，增强的加速等级 (E)\n\t\t\t\t\t\t\t 粒子产生：(Ln(min(M, H)) / 10 ^ (5-T)) * (min(M, H) / m) * 10^E\n\t\t",
    "Durability:": "持久性：",
    "Coolant cells hold heat.": "冷却电池保持热量。",
    "Potent  Dolorium Cell": "强效 Dolorium 电池",
    "Potent  Nefastium Cell": "强效 Nefastium 电池",
    "Potent  Plutonium Cell": "强效钚电池",
    "Potent  Seaborgium Cell": "强效𬭳电池",
    "Potent  Thorium Cell": "强效钍电池",
    "Potent  Uranium Cell": "强效铀电池",
    "Quad Uranium Cell": "四铀电池",
    "Reflectors generate an additional 1% of their base power per level of upgrade (additive with self).": "反射器每升级一次，就会额外产生 1% 的基础功率（与自身相加）。",
    "Reflectors last 100% longer per level of upgrade (additive with self).": "每升级一级，反射器的使用寿命延长 100%（与自身相加）。",
    "Reinforced Heat Exchangers 2": "加强型热交换器 2",
    "Seaborgium Cell  cells are automatically replaced when they become depleted. The replacement cell will cost 1.5 times the normal cost.": "Seaborgium Cell 电池在耗尽时会自动更换。更换电池的成本是正常成本的 1.5 倍。",
    "Seaborgium Cell  cells last twice as long per level of upgrade (multiplicative).": "Seaborgium Cell 电池每升级一级（乘法），持续时间是原来的两倍。",
    "Seaborgium Cell  cells produce 100% more power per level of upgrade (additive with self).": "Seaborgium Cell 电池每升级一级（与自身相加）可产生 100% 以上的功率。",
    "Sells 1% of your power each tick per level of upgrade (additive).": "每升一级（附加），每刻出售 1% 的能量。",
    "Thorium Cell  cells are automatically replaced when they become depleted. The replacement cell will cost 1.5 times the normal cost.": "钍电池电池耗尽时会自动更换。更换电池的成本是正常成本的 1.5 倍。",
    "Thorium Cell  cells last twice as long per level of upgrade (multiplicative).": "每升级一级（乘法），钍电池电池的使用寿命是原来的两倍。",
    "Thorium Cell  cells produce 100% more power per level of upgrade (additive with self).": "钍电池电池每升级一级（与自身相加）产生的功率增加 100%。",
    "Uranium Cell  cells produce 100% more power per level of upgrade (additive with self).": "Uranium Cell 电池每升级一级（与自身相加）可产生 100% 以上的功率。",
    "Venting manually is 10x as effective per level of upgrade (multiplicative).": "手动等待是每个升级级别（乘法）的 10 倍。",
    "Vents hold and vent 100% more heat per level of upgrade (additive with self).": "等待，保持并等待每升级 100% 的热量（与自身相加）。",
    "Your reactor no longer automatically removes heat from itself when it is below its maximum heat capacity. This makes Forceful Fusion easier to maintain.": "当您的反应堆低于其最大热容量时，它不再自动从自身带走热量。这使得 Forceful Fusion 更易于维护。",
    "Your reactor outlets no longer output more heat than what the connected vents can handle.": "您的反应器出口输出的热量不再超过连接的通风口可以处理的热量。",
    "+1 tick per second per level of upgrade.": "每升级一级，每秒 +1 滴答声。",
    "Add one column to the reactor for each level of the upgrade.": "为每个升级级别添加一列到反应器。",
    "Add one row to the reactor for each level of the upgrade.": "为每个升级级别添加一行到反应器。",
    "All of the above applies, however this will undo all your experiment upgrades and refund all your Exotic Particles.\n\t\t\t": "以上所有内容均适用，但这将撤消您的所有实验升级并退还您所有的异域粒子。\n\t\t\t",
    "Better Heat Control Operator": "更好的热控制操作员",
    "Enriched  Dolorium Cell": "富集 Dolorium 电池",
    "Enriched  Nefastium Cell": "富集Nefastium电池",
    "Enriched  Seaborgium Cell": "富集 Seaborgium 电池",
    "Enriched  Thorium Cell": "富钍电池",
    "Exchangers balance heat between themselves and adjacent components.\n\t\t\t\t\t\t\tBase heat capacity (C), Base transfer (T), Sum of all capacitor tiers (C": "交换器平衡自身和相邻组件之间的热量。\n\t\t\t\t\t\t\t基本热容量 (C)、基本转移 (T)、所有电容器层的总和 (C",
    "Expand Reactor Cols": "展开反应堆列",
    "Expand Reactor Rows": "展开反应器行",
    "Forceful Fission": "强力裂变",
    "Heat Control Operator": "热控操作员",
    "Heat Exchangers, Inlets and Outlets hold and exchange 100% more heat per level of upgrade (additive with self).": "每升级一级，热交换器、入口和出口可多容纳和交换 100% 的热量（与自身相加）。",
    "If capacitors are on a cool surface when they go over their maximum heat containment, the heat is vented directly into the reactor and the capacitor is replaced. The capacitor costs 10 times the normal cost.": "如果电容器在超过其最大热量遏制时处于凉爽的表面，则热量直接排放到反应堆中并更换电容器。电容器的成本是正常成本的 10 倍。",
    "Improved Alloys": "改良合金",
    "Improved Chronometers": "改进的计时器",
    "Increase the effect of capacitors on exchangers by 100% per level of upgrade (additive with self).": "每升级一级，电容器对交换器的影响增加 100%（与自身相加）。",
    "Increase the effect of capacitors on vents by 100% per level of upgrade (additive with self).": "每升级一级，电容器对通风口的影响增加 100%（与自身相加）。",
    "Increase the effect of plating on exchangers by 100% per level of upgrade (additive with self).": "每升级一级，电镀对交换器的影响增加 100%（与自身相加）。",
    "Increase the effect of plating on vents by 100% per level of upgrade (additive with self).": "每升级一级，电镀对通风口的影响增加 100%（与自身相加）。",
    "Inlets move heat from adjacent components into the reactor.\n\t\t\t\t\t\t\tBase transfer (T), Sum of all capacitor tiers (C": "入口将热量从相邻组件转移到反应器中。\n\t\t\t\t\t\t\t基本转移 (T)，所有电容器层的总和 (C",
    "Nefastium Cell  cells are automatically replaced when they become depleted. The replacement cell will cost 1.5 times the normal cost.": "Nefastium Cell 电池在耗尽时会自动更换。更换电池的成本是正常成本的 1.5 倍。",
    "Nefastium Cell  cells last twice as long per level of upgrade (multiplicative).": "Nefastium Cell 电池每升级一级（乘法），使用寿命就增加一倍。",
    "Nefastium Cell  cells produce 100% more power per level of upgrade (additive with self).": "Nefastium Cell 电池每升级一级（与自身相加）产生的功率增加 100%。",
    "Neutron Reflectors provide a power bonus to adjacent cells stacking additively with each other.\n\n\t\t": "中子反射器为相互叠加的相邻电池提供能量加成。\n\n\t\t",
    "Outlets move heat from the reactor into adjacent components.\n\t\t\t\t\t\t\tBase transfer (T), Sum of all capacitor tiers (C": "出口将热量从反应堆转移到相邻的组件。\n\t\t\t\t\t\t\t基本转移 (T)，所有电容器层的总和 (C",
    "Perpetual  Dolorium Cell": "永久毒气电池",
    "Perpetual  Nefastium Cell": "永久Nefastium电池",
    "Perpetual  Seaborgium Cell": "永久 Seaborgium 电池",
    "Perpetual  Thorium Cell": "永久钍电池",
    "Perpetual Capacitors": "永续电容器",
    "Plating holds 100% more heat per level of upgrade (additive with self).": "每升级一级，电镀的热量增加 100%（与自身相加）。",
    "Plutonium Cell  cells produce 100% more power per level of upgrade (additive with self).": "Plutonium Cell 电池每升级一级（与自身相加）产生的功率增加 100%。",
    "Outlets move heat from the reactor into adjacent components.\n\t\t\t\t\t\t\tBase transfer (T), Sum of all capacitor tiers (C": "出口将热量从反应堆转移到相邻的组件。\n\t\t\t\t\t\t\t基础转移（T），所有电容器层的总和（C",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t\t\t\t\t": "\t\t\t\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Exotic Particles": "奇异粒子",
    "Reduce your Current Heat to ": "将您当前的热量减少到 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Rebooting the reactor will remove all parts, regular upgrades and money. Only your current experimental upgrades and EP will stay with you.": "重新启动反应堆将移除所有部件、定期升级和金钱。 只有您当前的实验性升级和 EP 将与您同在。",
    "All of the above applies, however this will undo all your experiment upgrades and refund all your Exotic Particles.": "以上所有内容均适用，但这将撤消您的所有实验升级并退还您所有的异域粒子。",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);