/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "Improvement:": "改进：",
    "New Features:": "新功能：",
    "Options": "选项",
    "Patch Notes": "更新日志",
    "Upgrades": "升级",
    "You can no longer place locked components^2.": "您不能再放置锁定的组件^2。",
    "Experimental Upgrades": "实验性升级",
    "Experiments": "实验",
    "Export save": "导出存档",
    "Faster repaint time by layering frequently updated ui (Improve fps/lag)": "通过对频繁更新的 ui 进行分层来加快重绘时间（提高 fps/lag）",
    "Faster tick timing (faster loading after offline)": "更快的滴答时间（离线后加载更快）",
    "Features:": "特征：",
    "Fixed an issue with game loop firing too often": "修复了游戏循环触发过于频繁的问题",
    "Fixed sell costs for some components": "某些组件的固定出售成本",
    "Fixed support for larger touch devices to allow for selling, etc": "修复了对更大触摸设备的支持以允许出售等",
    "Fixes extreme plating adding to max power despite not being bought yet": "尽管尚未购买，但修复了极端电镀以增加最大功率",
    "Fixes Heat Control Operator adding heat": "修复了热量控制操作员添加热量的问题",
    "Fixes heat outlet heat distribution bug with multi-tier setup": "修复了多层设置的热出口热量分布错误",
    "Fixes reflector ui load bug": "修复反射器 ui 加载错误",
    "Greatly improve performance": "大大提高性能",
    "Heat": "热量",
    "Heavily optimized the protium code that I ruined.": "对我破坏的 氕 代码进行了大量优化。",
    "Help": "帮助",
    "Hold keys in bracket and click to use the macro": "按住括号中的键并单击以使用宏",
    "Implemented Chlorophymium.": "实施了绿藻。",
    "Import save": "导入存档",
    "Changes": "变化",
    "Changes:": "变化：",
    "Checkered fill (ctrl+alt+shift)": "方格填充（ctrl+alt+shift）",
    "Click to Select": "点击选择",
    "Click to Upgrade": "点击升级",
    "Column (alt)": "列（alt）",
    "Components": "组件",
    "Coolant Innovation.": "冷却液创新。",
    "Current": "当前的",
    "Disable Auto Buy": "禁用自动购买",
    "Disable Auto Sell": "禁用自动出售",
    "Disable Heat Controller": "禁用热控制器",
    "Disable Offline Tick": "禁用离线Tick",
    "Disable Speed Hack": "禁用 Speed Hack",
    "Don't filter by part (shift)": "不要按零件过滤（shift）",
    "Download save": "下载保存",
    "Enable Google Drive Online Save": "启用 谷歌在线云盘 保存",
    "Enable Heat Controller": "启用热控制器",
    "Enable Local Save Only": "仅启用本地保存",
    "Enable Speed Hack": "启用速度破解",
    "Cancel": "取消",
    "A modification of": "修改",
    "A reset button!": "一个重置按钮！",
    "About": "关于",
    "Added individual experimental Particle Accelerator upgrades": "添加了单个实验性粒子加速器升级",
    "Added mitochdonrium.": "添加了线粒体。",
    "Added Objectives": "添加的目标",
    "Added patch notes": "添加了补丁说明",
    "Additional hotkeys/macro:": "其他热键/宏：",
    "Additions:": "补充：",
    "All accelerators no hold a max of 100 heat to prevent abuse of higher tiers.": "所有加速器都不能容纳最多 100 个热量，以防止滥用更高等级。",
    "Approximate EP per tick display.": "每个tick度显示的近似 EP。",
    "Back to Reactor": "回到反应堆",
    "Bang For Your Buck.": "全力以赴。",
    "Based on": "基于",
    "Basic Overview": "基本概述",
    "Buch": "布赫",
    "Bug fixes:": "Bug修复：",
    "Bug Fixes:": "Bug修复：",
    "Vent and Plating boosts for components multiply together instead of adding.": "排气和电镀促进组件相乘而不是相加。",
    "The game is immediately paused on loading or importing.": "游戏在加载或导入时立即暂停。",
    "Tick catchup": "Tick catchup",
    "Tile queue now buys as many as possible per tick": "瓷砖队列现在每次购买尽可能多",
    "UI based on": "用户界面基于",
    "Unpause": "取消暂停",
    "Upgrade tick catchup to offline ticks!": "将 tick catchup 升级为 离线tick！",
    "Usage": "用法",
    "Increase utility prices.": "提高公用事业价格。",
    "last tick)": "上个 tick）",
    "Left+right click triggering double click function and deleting tiles": "左键+右键触发双击功能并删除图块",
    "Less cpu usage when not on reactor tile panel": "不在反应器瓷砖面板上时减少 cpu 使用率",
    "Less lag spike for UI, tooltip": "UI、工具提示的层数减少",
    "Made help helpful.": "使帮助有所帮助。",
    "Make sure background get updated when placing plating so it doesn't get stuck on red": "确保在放置电镀时背景得到更新，这样它就不会卡在红色上",
    "Many upgrades now have a second tier.": "许多升级现在都有第二层。",
    "Moved the Coolant Innovation upgrade.": "移动冷却液创新升级。",
    "Multiple Exotic Particles gained when over 100% chance": "超过 100% 的几率获得多个奇异粒子",
    "New upgrade which prevents outlets from outputting more than what the vent can handle": "新升级可防止出口的输出超过通风口的处理能力",
    "Objective": "目标",
    "Offline Tick": "离线Tick",
    "Particle accelerators now have a standard upgrade.": "粒子加速器现在有一个标准升级。",
    "Parts": "零件",
    "Pause": "暂停",
    "per tick)": "每tick）",
    "Percentage bar and overheating redness are now updated in steps (reduce repainting)": "百分比条和过热发红现在分步更新（减少重绘）",
    "Place your first component in the reactor": "将您的第一个组件放入反应器中",
    "Platings (and possibly other things) now give 100% of their cost back when sold": "镀层（可能还有其他东西）现在在售出时返还 100% 的成本",
    "Power": "功率",
    "Reactor": "反应堆",
    "Reactor Incremental": "反应堆增量",
    "Reactor Knockoff": "反应堆仿制品",
    "Reactor meltdowns no longer instantly save the game.": "反应堆熔毁不再立即拯救游戏。",
    "Reboot and refund": "重启和退款",
    "Reboot for": "重新启动",
    "Reflectors now start with a base % greater than 0": "反射器现在以大于 0 的基本百分比开始",
    "Removed old Particle Accelerator upgrades": "移除旧的粒子加速器升级",
    "Reorganized upgrades.": "重组升级。",
    "Replaced every texture with similar ones of my own.": "用我自己的类似纹理替换了每个纹理。",
    "Replacing now works with same category parts, eg: downgrading, switching cell type": "替换现在适用于相同类别的部件，例如：降级、切换电池类型",
    "Replacing tiles is now faster": "更换瓷砖现在更快",
    "Replacing tiles with another now reimburse the amount for the part": "现在用另一个替换瓷砖可以补偿该部分的金额",
    "Reset game": "重置游戏",
    "Retexture:": "重新构造：",
    "Right click no longer buy stuff": "右键不再买东西",
    "Row (ctrl)": "行 (ctrl)",
    "Save data exporting and importing": "保存数据导出和导入",
    "Save game": "保存游戏",
    "Sci-fi User Interface Elements": "科幻用户界面元素",
    "See Patch Notes": "查看补丁说明",
    "Sell": "出售",
    "Shift/Double click now works on empty tiles": "Shift/双击现在适用于空瓷砖",
    "Signific code changes that shouldn't (but may) affect gameplay": "不应（但可能）影响游戏玩法的重大代码更改",
    "Spacing options (number)": "间距选项（数量）",
    "Speed Hack": "极速破解",
    "Speed hack toggle, throw more stuff into their own layer and thus reduce paint time (at the cost of memory)": "Speed hack切换，将更多的东西扔到自己的图层中，从而减少绘制时间（以内存为代价）",
    "Stats": "状态",
    "Styling fixes to \"pages\"": "对“页面”的样式修复",
    "% of max)\n\t\t": "% 最大)\n\t\t",
    "Dual Uranium Cell": "双铀电池",
    "Enable Auto Buy": "启用自动购买",
    "Enable Auto Sell": "启用自动出售",
    "Sell all your power by clicking \"Sell\"": "通过点击“出售”出售你所有的功率",
    "Uranium Cell": "铀电池",
    "% per tick (": "% 每 tick (",
    "), Improved Heatsinks level (S), Active Venting level (A)\n\t\t\t\t\t\t\tVentillation:\tV * (1 + A * C": "), 改进的散热器级别 (S), 主动通风级别 (A)\n\t\t\t\t\t\t\t通风：\tV * (1 + A * C",
    "), Sum of all plating tiers (P": "), 所有电镀层的总和 (P",
    "), Reinforced Heat Exchnagers level (R), Active Exchnagers level (A)\n\t\t\t\t\t\t\tTransfer Rate:\tT * (1 + A * C": "), 强化换热器等级 (R), 主动换热器等级 (A)\n\t\t\t\t\t\t\t 传输率：\tT * (1 + A * C",
    "/ 200)\n\t\t\t\t\t\t\tHeat Capacity:\tC * (1 + A * C": "/ 200)\n\t\t\t\t\t\t\t热容量：\tC * (1 + A * C",
    "Capacitors increase the total energy capacity of the reactor.\n\n\t\t": "电容器增加了反应堆的总功率容量。\n\n\t\t",
    "EP chance:": "EP几率：",
    "Sells for:": "出售：",
    "Power:": "功率：",
    "Heat:": "热量：",
    "Power cells generate heat and power. Each cell in a given tile gives a pulse to each adjacent tile. Heat and power scale with the number of pulses recieved.\n\t\t\t\t\t\t\tPulses Recieved (U), Single cell base power (P), Single cell base heat (H), Cell count (C)\n\t\t\t\t\t\t\t(M) 1 for single, 4 for double, 12 for quad\n\t\t\t\t\t\t\tPower: P * (M + U)\n\t\t\t\t\t\t\tHeat: H * (M + U)^2/C\n\n\t\t": "电池产生热量和电能。 给定瓦片中的每个电池都被给予每个相邻瓦片的脉冲。 热量和功率随接收到的脉冲数量而变化。\n\t\t\t\t\t\t\t 接收到的脉冲 (U)、单电池基础功率 (P)、单电池基础热量 (H)、电池计数(C)\n\t\t\t\t\t\t\t(M) 1为单人，4人为双人，12人为四人\n\t\t\t\t\t\t\t功率： P * (M + U)\n\t\t\t\t\t\t\t热量：H * (M + U)^2/C\n\n\t\t",
    "Vents dissipate contained heat.\n\t\t\t\t\t\t\tBase heat capacity (C), Base ventillation (V), Sum of all capacitor tiers (C": "通风口散发热量。\n\t\t\t\t\t\t\t 基本热容量 (C)、基本通风量 (V)、所有电容器层的总和 (C",
    "platings increase the total heat capacity of the reactor.\n\n\t\t": "镀层增加了反应器的总热容量。\n\n\t\t",
    "Particle Accelerators produce exotic particles based on the heat passing through them each tick.\n\t\t\t\t\t\t\tMax Heat BEFORE upgrades (m), Max Heat (M), Heat throughput (H), Tier (T), Enhanced Acceleration Levle (E)\n\t\t\t\t\t\t\tParticle production: (Ln(min(M, H)) / 10 ^ (5-T)) * (min(M, H) / m) * 10^E\n\t\t": "粒子加速器根据每tick通过它们的热量产生奇异粒子。\n\t\t\t\t\t\t\t升级前的最大热量 (m), 最大热量 (M), 热通量 (H),等级 (T)，增强的加速等级 (E)\n\t\t\t\t\t\t\t 粒子产生：(Ln(min(M, H)) / 10 ^ (5-T)) * (min(M, H) / m) * 10^E\n\t\t",
    "Durability:": "持久性：",
    "Coolant cells hold heat.": "冷却电池保持热量。",
    "Potent  Dolorium Cell": "强效 Dolorium 电池",
    "Potent  Nefastium Cell": "强效 氖 电池",
    "Potent  Plutonium Cell": "强效钚电池",
    "Potent  Seaborgium Cell": "强效𬭳电池",
    "Potent  Thorium Cell": "强效钍电池",
    "Potent  Uranium Cell": "强效铀电池",
    "Quad Uranium Cell": "四铀电池",
    "Reflectors generate an additional 1% of their base power per level of upgrade (additive with self).": "反射器每升级一次，就会额外产生 1% 的基础功率（与自身相加）。",
    "Reflectors last 100% longer per level of upgrade (additive with self).": "每升级一级，反射器的使用寿命延长 100%（与自身相加）。",
    "Reinforced Heat Exchangers 2": "加强型热交换器 2",
    "Seaborgium Cell  cells are automatically replaced when they become depleted. The replacement cell will cost 1.5 times the normal cost.": "𬭳电池 电池在耗尽时会自动更换。更换电池的成本是正常成本的 1.5 倍。",
    "Seaborgium Cell  cells last twice as long per level of upgrade (multiplicative).": "𬭳电池 电池每升级一级（乘法），持续时间是原来的两倍。",
    "Seaborgium Cell  cells produce 100% more power per level of upgrade (additive with self).": "𬭳电池 电池每升级一级（与自身相加）可产生 100% 以上的功率。",
    "Sells 1% of your power each tick per level of upgrade (additive).": "每升一级（附加），每tick出售 1% 的功率。",
    "Thorium Cell  cells are automatically replaced when they become depleted. The replacement cell will cost 1.5 times the normal cost.": "钍电池电池耗尽时会自动更换。更换电池的成本是正常成本的 1.5 倍。",
    "Thorium Cell  cells last twice as long per level of upgrade (multiplicative).": "每升级一级（乘法），钍电池电池的使用寿命是原来的两倍。",
    "Thorium Cell  cells produce 100% more power per level of upgrade (additive with self).": "钍电池电池每升级一级（与自身相加）产生的功率增加 100%。",
    "Uranium Cell  cells produce 100% more power per level of upgrade (additive with self).": "Uranium Cell 电池每升级一级（与自身相加）可产生 100% 以上的功率。",
    "Venting manually is 10x as effective per level of upgrade (multiplicative).": "手动等待是每个升级级别（乘法）的 10 倍。",
    "Vents hold and vent 100% more heat per level of upgrade (additive with self).": "等待，保持并等待每升级 100% 的热量（与自身相加）。",
    "Your reactor no longer automatically removes heat from itself when it is below its maximum heat capacity. This makes Forceful Fusion easier to maintain.": "当您的反应堆低于其最大热容量时，它不再自动从自身带走热量。这使得 Forceful Fusion 更易于维护。",
    "Your reactor outlets no longer output more heat than what the connected vents can handle.": "您的反应器出口输出的热量不再超过连接的通风口可以处理的热量。",
    "+1 tick per second per level of upgrade.": "每升级一级，每秒 +1 tick。",
    "Add one column to the reactor for each level of the upgrade.": "为每个升级级别添加一列到反应器。",
    "Add one row to the reactor for each level of the upgrade.": "为每个升级级别添加一行到反应器。",
    "All of the above applies, however this will undo all your experiment upgrades and refund all your Exotic Particles.\n\t\t\t": "以上所有内容均适用，但这将撤消您的所有实验升级并退还您所有的异域粒子。\n\t\t\t",
    "Better Heat Control Operator": "更好的热控制操作员",
    "Enriched  Dolorium Cell": "富Dolorium电池",
    "Enriched  Nefastium Cell": "富氖电池",
    "Enriched  Seaborgium Cell": "富𬭳电池",
    "Enriched  Thorium Cell": "富钍电池",
    "Exchangers balance heat between themselves and adjacent components.\n\t\t\t\t\t\t\tBase heat capacity (C), Base transfer (T), Sum of all capacitor tiers (C": "交换器平衡自身和相邻组件之间的热量。\n\t\t\t\t\t\t\t基本热容量 (C)、基本转移 (T)、所有电容器层的总和 (C",
    "Expand Reactor Cols": "展开反应堆列",
    "Expand Reactor Rows": "展开反应器行",
    "Forceful Fission": "强力裂变",
    "Heat Control Operator": "热控操作员",
    "Heat Exchangers, Inlets and Outlets hold and exchange 100% more heat per level of upgrade (additive with self).": "每升级一级，热交换器、入口和出口可多容纳和交换 100% 的热量（与自身相加）。",
    "If capacitors are on a cool surface when they go over their maximum heat containment, the heat is vented directly into the reactor and the capacitor is replaced. The capacitor costs 10 times the normal cost.": "如果电容器在超过其最大热量遏制时处于凉爽的表面，则热量直接排放到反应堆中并更换电容器。电容器的成本是正常成本的 10 倍。",
    "Improved Alloys": "改良合金",
    "Improved Chronometers": "改进的计时器",
    "Increase the effect of capacitors on exchangers by 100% per level of upgrade (additive with self).": "每升级一级，电容器对交换器的影响增加 100%（与自身相加）。",
    "Increase the effect of capacitors on vents by 100% per level of upgrade (additive with self).": "每升级一级，电容器对通风口的影响增加 100%（与自身相加）。",
    "Increase the effect of plating on exchangers by 100% per level of upgrade (additive with self).": "每升级一级，电镀对交换器的影响增加 100%（与自身相加）。",
    "Increase the effect of plating on vents by 100% per level of upgrade (additive with self).": "每升级一级，电镀对通风口的影响增加 100%（与自身相加）。",
    "Inlets move heat from adjacent components into the reactor.\n\t\t\t\t\t\t\tBase transfer (T), Sum of all capacitor tiers (C": "入口将热量从相邻组件转移到反应器中。\n\t\t\t\t\t\t\t基本转移 (T)，所有电容器层的总和 (C",
    "Nefastium Cell  cells are automatically replaced when they become depleted. The replacement cell will cost 1.5 times the normal cost.": "氖电池 电池在耗尽时会自动更换。更换电池的成本是正常成本的 1.5 倍。",
    "Nefastium Cell  cells last twice as long per level of upgrade (multiplicative).": "氖电池 电池每升级一级（乘法），使用寿命就增加一倍。",
    "Nefastium Cell  cells produce 100% more power per level of upgrade (additive with self).": "氖电池 电池每升级一级（与自身相加）产生的功率增加 100%。",
    "Neutron Reflectors provide a power bonus to adjacent cells stacking additively with each other.\n\n\t\t": "中子反射器为相互叠加的相邻电池提供功率加成。\n\n\t\t",
    "Outlets move heat from the reactor into adjacent components.\n\t\t\t\t\t\t\tBase transfer (T), Sum of all capacitor tiers (C": "出口将热量从反应堆转移到相邻的组件。\n\t\t\t\t\t\t\t基本转移 (T)，所有电容器层的总和 (C",
    "Perpetual  Dolorium Cell": "永久Dolorium电池",
    "Perpetual  Nefastium Cell": "永久氖电池",
    "Perpetual  Seaborgium Cell": "永久𬭳电池",
    "Perpetual  Thorium Cell": "永久钍电池",
    "Perpetual Capacitors": "永续电容器",
    "Plating holds 100% more heat per level of upgrade (additive with self).": "每升级一级，电镀的热量增加 100%（与自身相加）。",
    "Plutonium Cell  cells produce 100% more power per level of upgrade (additive with self).": "钚电池 电池每升级一级（与自身相加）产生的功率增加 100%。",
    "Outlets move heat from the reactor into adjacent components.\n\t\t\t\t\t\t\tBase transfer (T), Sum of all capacitor tiers (C": "出口将热量从反应堆转移到相邻的组件。\n\t\t\t\t\t\t\t基础转移（T），所有电容器层的总和（C",
    "Plutonium Cell  cells are automatically replaced when they become depleted. The replacement cell will cost 1.5 times the normal cost.": "钚电池 电池耗尽时会自动更换。 更换电池的成本是正常成本的 1.5 倍。",
    "Enriched  Plutonium Cell": "富钚电池",
    "Enriched  Uranium Cell": "富铀电池",
    "Improved Coolant Cells": "改进的冷却液电池",
    "Improved Neutron Reflection": "改进的中子反射",
    "Improved Piping": "改进的管道",
    "Improved Power Lines is no no longer doing double the intended effect.": "改进的功率线不再是预期效果的两倍。",
    "Improved Reflector Density": "改进的反射器密度",
    "Increase utility prices upgrade.": "提高公用事业价格升级。",
    "Mitochdonrium.": "线粒体。",
    "Perpetual  Plutonium Cell": "永久钚电池",
    "Perpetual Reflectors": "永久反射器",
    "Perpetual Experimental Cell upgrades.": "永久实验电池升级。",
    "Uranium Cell  cells last twice as long per level of upgrade (multiplicative).": "铀电池的持续时间是每级升级的两倍(倍增)。",
    "Vent and Plating boosts for components multiply together instead of adding and are half as strong.": "组件的排气和电镀增强相乘而不是相加，强度只有一半。",
    "You can no longer place locked components.": "您不能再放置锁定的组件。",
    "Disclaimer": "免责声明",
    "This section is a work in progress!\n\t\t\t\t\t\t\tInformation in this section may be inaccurate or incomplete.\n\t\t\t\t\t\t\tTake every piece of information with a grain of salt!": "本节正在进行中！\n\t\t\t\t\t\t\t 本节中的信息可能不准确或不完整。\n\t\t\t\t\t\t\take 每一条信息都撒了一粒盐！",
    "The internal code for accelerators has been changed, old setups should still work": "加速器的内部代码已更改，旧设置应该仍然有效",
    "Unleashed Cells no longer reduces heat related effects from experimental cell upgrades.": "释放电池 不再减少实验性电池升级带来的与热量相关的影响。",
    "Window Width is now constant.": "窗口宽度现在是恒定的。",
    "Particle Accelerators produce exotic particles based on the heat passing through them each tick.\n\t\t\t\t\t\t\tMax Heat BEFORE upgrades (m), Max Heat (M), Heat throughput (H), Tier (T), Enhanced Acceleration Levle (E)\n\t\t\t\t\t\t\tParticle production: (Ln(min(M, H)) / 10 ^ (5-T)) * (min(M, H) / m) * 10^E\n\t\t\t\t\t\t\tLn(x) - The natural log (base e) of x\n\t\t\t\t\t\t\tmin(x, y) - the lowest value between x and y\n\t\t": "粒子加速器根据每tick通过它们的热量产生奇异粒子。\n\t\t\t\t\t\t\t升级前的最大热量 (m), 最大热量 (M), 热通量 (H), 层 (T)，增强的加速等级 (E)\n\t\t\t\t\t\t\t粒子产生：(Ln(min(M, H)) / 10 ^ (5-T)) * ( min(M, H) / m) * 10^E\n\t\t\t\t\t\t\tLn(x) - x\n\t\t\t 的自然对数（以 e 为底） \t\t\t\tmin(x, y) - x 和 y 之间的最小值\n\t\t",
    "Quick fix - August 9th 2022": "快速修复 - 2022 年 8 月 9 日",
    "Re-enabled Blackhole Accelerator upgrade (use at your own risk)": "重新启用黑洞加速器升级（使用风险自负）",
    "Reduce Heat to 0 objective no longer requires you to manually reduce heat.": "将热量减少到 0 目标不再需要您手动减少热量。",
    "Removed all traces of Google Drive Online Save (It wasn't useable anyway)": "删除了 Google Drive Online Save 的所有痕迹（无论如何都无法使用）",
    "Chlorophymium.": "绿藻。",
    "Coolant cells hold heat.\n\n\t\t": "冷却液电池保持热量。\n\n\t\t",
    "Coolant Innovation upgrade.": "冷却液创新升级。",
    "Disabled the ability to unlock black hole accelerators as they are 100% broken.": "禁用解锁黑洞加速器的功能，因为它们 100% 损坏。",
    "Exchangers now consider plating and capacitors when deciding how much heat to transfer to vents": "交换器现在在决定将多少热量传递到通风口时会考虑电镀和电容器",
    "Extreme Capacitors now add the proper amount of heat based": "极限电容器现在添加适量的热量",
    "Fixes": "修复",
    "Normalized button size for each section.": "每个部分的标准化按钮大小。",
    "NOTE: this is every ZenMod change (that I remember XD). Each section is in chronological order": "注意：这是 ZenMod 的每一次更改（我记得 XD）。 每个部分按时间顺序排列",
    "Be sure to double check your cooling capability and heat generation if you are using experimental cells! This fix may cause an unexpected increase in heat generation!": "如果您使用的是实验电池，请务必仔细检查您的冷却能力和热量产生！ 此修复可能会导致热量产生意外增加！",
    "Bug fixes": "Bug修复",
    "Bug Fixes": "Bug修复",
    "Added flavor text to every component.": "为每个组件添加了描述文本。",
    "Added tuning slider for Auto Sell.": "为自动出售添加了调整滑块。",
    "Added tuning slider for Heat Controller.": "为热控制器添加了调整滑块。",
    "Protium Cells": "氕电池",
    "Protium cells are automatically replaced when they become depleted. The replacement cell will cost 1.5 times the normal cost.": "氕电池在耗尽时会自动更换。更换电池的成本是正常成本的 1.5 倍。",
    "Protium cells last half as long and product twice as much power and heat per level (multiplicative).": "氕 电池的使用寿命是原来的一半，每级（乘法）产生两倍的功率和热量。",
    "Quantum Buffering": "量子缓冲",
    "Reduce the cost growth of standard upgrades by 10% per level (multiplicative).": "将标准升级的成本增长每级降低 10%（乘法）。",
    "Reduces the cost scaling of standard cooling upgrades by 10% per level (additive with self).": "将标准冷却升级的成本缩放每级降低 10%（与自身相加）。",
    "Reflectors gain an additional 100% of their base power reflection per level of upgrade (additive with self).": "反射器每升级一次，就会额外获得 100% 的基础功率反射（与自身相加）。",
    "Singularity Harnessing": "奇点利用",
    "Temporarily disabled": "暂时禁用",
    "The most common nuclear fuel.": "最常见的核燃料。",
    "Thermionic Conversion": "热离子转换",
    "Ultracryonics": "超低温",
    "Underground Heat Extraction": "地下热提取",
    "Unleashed Cells": "释放电池",
    "Unstable Protium": "不稳定的氕",
    "Vortex Cooling": "涡流冷却",
    "Vortex Extraction": "涡流提取",
    "Laboratory": "实验室",
    "Lunar Chlorophymium": "月球绿藻",
    "Micro Capacitance": "微电容",
    "Mitochondrium Cells": "线粒体电池",
    "Mitochondrium cells are automatically replaced when they become depleted. The replacement cell will cost 1.5 times the normal cost.": "线粒体电池在耗尽时会自动更换。更换电池的成本是正常成本的 1.5 倍。",
    "Mitochondrium energy cap and heat is 10x (multiplicative).": "线粒体功率上限和热量是 10 倍（乘法）。",
    "Perpetual Chlorophymium": "永久绿藻",
    "Perpetual Mitochondrium": "永久线粒体",
    "Perpetual Protium": "永久的氕",
    "Phlembotinum Core": "蛇尾草核心",
    "Experimental Capacitance": "实验电容",
    "Explosive Ejection": "爆炸弹射",
    "F1 - August 13th 2022": "F1 - 2022 年 8 月 13 日",
    "Fluid Hyperdynamics": "流体超动力学",
    "Fractal Piping": "分形管道",
    "Full Spectrum Reflectors": "全光谱反射器",
    "Heat Reflection": "热反射",
    "Heat vents and exchangers hold two times their base heat per level of upgrade (multiplicative).": "每个升级级别（乘法），散热孔和交换器的基本热量是其基础热量的两倍。",
    "Heat vents, exchangers, inlets and outlets are two times as effective per level of upgrade (multiplicative).": "每个升级级别（乘法）的散热孔、交换器、入口和出口的效率是其两倍。",
    "Improved Advanced Particle Accelerator": "改进的高级粒子加速器",
    "Improved Basic Particle Accelerator": "改进的基本粒子加速器",
    "Improved Black Hole Particle Accelerator": "改进的黑洞粒子加速器",
    "Improved Super Particle Accelerator": "改进的超级粒子加速器",
    "Improved Ultimate Particle Accelerator": "改进的终极粒子加速器",
    "Improved Wonderous Particle Accelerator": "改进的奇妙粒子加速器",
    "Increase profit from selling power by 10% per level (multiplicative).": "每级增加 10% 的销售能力利润（乘法）。",
    "Increase the base heat and power storage of the reactor by four times per level of upgrade (multiplicative).": "每个升级级别（乘法）将反应堆的基础热量和功率存储增加四倍。",
    "Increase the maximum heat that Advanced Particle Accelerators can use and contain to create Exotic Particles by 100% per level of upgrade (additive with self).": "将高级粒子加速器可以使用和容纳的最大热量增加 100%，每升级一级（与自身相加）。",
    "Increase the maximum heat that Basic Particle Accelerators can use and contain to create Exotic Particles by 100% per level of upgrade (additive with self).": "每升级一级，基本粒子加速器可以使用和容纳的最大热量来制造奇异粒子，增加 100%（与自身相加）。",
    "Increase the maximum heat that Black Hole Particle Accelerators can use and contain to create Exotic Particles by 100% per level of upgrade (additive with self).": "将黑洞粒子加速器可以使用和容纳的最大热量增加 100%，每升级一级（与自身相加）。",
    "Increase the maximum heat that Super Particle Accelerators can use and contain to create Exotic Particles by 100% per level of upgrade (additive with self).": "将超级粒子加速器可以使用和容纳的最大热量增加 100%，每升级一级（与自身相加）。",
    "Increase the maximum heat that Ultimate Particle Accelerators can use and contain to create Exotic Particles by 100% per level of upgrade (additive with self).": "将终极粒子加速器可以使用和容纳的最大热量增加 100%，每升级一级（与自身相加）。",
    "Increase the maximum heat that Wonderous Particle Accelerators can use and contain to create Exotic Particles by 100% per level of upgrade (additive with self).": "每升一级（与自身相加），将奇妙粒子加速器可以使用和容纳来制造奇异粒子的最大热量提高 100%。",
    "Increase Utility Prices": "提高公用事业价格",
    "Infused Cells": "注入电池",
    "Allows you to use Black Hole Particle Accelerators. When purchased, the EP cost of other experimental part upgrades increases.": "允许您使用黑洞粒子加速器。购买后，其他实验部件升级的 EP 成本会增加。",
    "Allows you to use Charged Reactor Plating. When purchased, the EP cost of other experimental part upgrades increases.": "允许您使用带电反应堆电镀。购买后，其他实验部件升级的 EP 成本会增加。",
    "Allows you to use chlorophymium cells.": "允许您使用绿藻电池。",
    "Allows you to use Extreme Capacitors. When purchased, the EP cost of other experimental part upgrades increases.": "允许您使用极限电容器。购买后，其他实验部件升级的 EP 成本会增加。",
    "Allows you to use Extreme Heat Exchangers. When purchased, the EP cost of other experimental part upgrades increases.": "允许您使用极限热交换器。购买后，其他实验部件升级的 EP 成本会增加。",
    "Allows you to use Extreme Heat Inlets. When purchased, the EP cost of other experimental part upgrades increases.": "允许您使用极热入口。购买后，其他实验部件升级的 EP 成本会增加。",
    "Allows you to use Extreme Heat Outlets. When purchased, the EP cost of other experimental part upgrades increases.": "允许您使用极热出口。购买后，其他实验部件升级的 EP 成本会增加。",
    "Allows you to use Extreme Vents. When purchased, the EP cost of other experimental part upgrades increases.": "允许您使用 Extreme Vents。购买后，其他实验部件升级的 EP 成本会增加。",
    "Allows you to use mitochondrium cells.": "允许您使用线粒体电池。",
    "Allows you to use protium cells.": "允许您使用 氕 电池。",
    "Allows you to use Thermal Neutron Reflectors. When purchased, the EP cost of other experimental part upgrades increases.": "允许您使用热中子反射器。购买后，其他实验部件升级的 EP 成本会增加。",
    "Allows you to use Thermionic Coolant Cells. When purchased, the EP cost of other experimental part upgrades increases.": "允许您使用热离子冷却液电池。购买后，其他实验部件升级的 EP 成本会增加。",
    "Bandage solution - August 10th 2022": "绷带解决方案 - 2022 年 8 月 10 日",
    "Bang For Your Buck": "物超所值",
    "Bang For Your Buck upgrade.": "物有所值升级。",
    "Capacitors and platings provide twice as much reactor power and heat capacity, and capacitors can contain twice as much heat per level of upgrade (multiplicative).": "电容器和镀层提供两倍的反应堆功率和热容量，并且电容器每升级一级（乘法）可以包含两倍的热量。",
    "Chlorophymium Cells": "绿藻电池",
    "Chlorophymium cells are automatically replaced when they become depleted. The replacement cell will cost 1.5 times the normal cost.": "Chlorophymium 电池在耗尽时会自动更换。更换电池的成本是正常成本的 1.5 倍。",
    "Chlorophymium power production is affected by the time of day 100% more (multiplicative).": "Chlorophymium 发电量受一天中时间的影响增加 100%（乘法）。",
    "Coolant cells hold two times their base heat per level of upgrade (multiplicative).": "每升级一级（乘法），冷却液电池的基本热量就会增加两倍。",
    "Coolant Innovation": "冷却液创新",
    "Double Click no longer acts as shit + click": "双击不再充当狗屎+点击",
    "Each fuel cell produces an additional 100% base power per level of upgrade (additive with self).": "每升级一级，每个燃料电池都会额外产生 100% 的基础功率（与自身相加）。",
    "Each fuel cell produces two times their base heat and power per level of upgrade (multiplicative).": "每个燃料电池每升级一次（乘法）产生两倍的基本热量和功率。",
    "Enables experimental upgrades.": "启用实验性升级。",
    "Energized Chlorophymium": "充能的绿藻",
    "Active Exchangers": "主动交换器",
    "Active Exchangers 2": "主动交换器 2",
    "Active Venting": "主动排气",
    "Active Venting 2": "主动排气 2",
    "Capacitors hold +100% power and heat per level of upgrade (additive with self).": "每升级一级，电容器可保持 +100% 的功率和热量（与自身相加）。",
    "Cells produce 1% more power at 1k heat, 2% power at 1m heat etc. per level of upgrade (additive with self).": "电池在 1k 热量下产生 1% 的功率，在 1m 热量下产生 2% 的功率等。每个升级级别（与自身相加）。",
    "Coolant cells hold 100% more heat per level of upgrade (additive with self).": "每升级一级，冷却液电池的热量就会增加 100%（与自身相加）。",
    "Dolorium Cell  cells are automatically replaced when they become depleted. The replacement cell will cost 1.5 times the normal cost.": "Dolorium Cell 电池耗尽时会自动更换。更换电池的成本是正常成本的 1.5 倍。",
    "Dolorium Cell  cells last twice as long per level of upgrade (multiplicative).": "Dolorium Cell 电池每升级一级（乘法）持续时间是原来的两倍。",
    "Dolorium Cell  cells produce 100% more power per level of upgrade (additive with self).": "Dolorium Cell 电池每升级一级（与自身相加）产生的功率增加 100%。",
    "Each capacitor increases the amount of heat that exchangers can exchange by 0.5% per level of upgrade per level of capacitor (additive with self).": "每个电容器每升级每级电容器，交换器可以交换的热量增加 0.5%（与自身相加）。",
    "Each capacitor increases the amount of heat that vents can vent by 0.5% per level of upgrade per level of capacitor (additive with self).": "每升一级电容器，每升一级电容器，通风口可以排出的热量增加 0.5%（与自身相加）。",
    "Each plating increases the amount of heat that exchangers can exchange by 0.5% per level of upgrade per level of plating (additive with self).": "每层镀层每升级一层镀层，交换器可以交换的热量增加 0.5%（与自身相加）。",
    "Each plating increases the amount of heat that vents can vent by 0.5% per level of upgrade per level of plating (additive with self).": "每层镀层每升级一层镀层，通风孔可以排放的热量增加 0.5%（与自身相加）。",
    "Improved Alloys 2": "改良合金 2",
    "Improved Coolant Cells 2": "改进的冷却液电池 2",
    "Improved Heat Exchangers": "改进的热交换器",
    "Improved Heat Exchangers 2": "改进的热交换器 2",
    "Improved Heat Vents": "改进的散热孔",
    "Improved Heat Vents 2": "改进的散热孔 2",
    "Improved Heatsinks": "改进的散热器",
    "Improved Heatsinks 2": "改进的散热器 2",
    "Improved Neutron Reflection 2": "改进的中子反射 2",
    "Improved Power Lines": "改进的电源线",
    "Improved Power Lines 2": "改进的电源线 2",
    "Improved Reflector Density 2": "改进的反射器密度 2",
    "Improved Wiring": "改进的接线",
    "Improved Wiring 2": "改进的接线 2",
    "Initial - August 12th 2022": "初始 - 2022 年 8 月 12 日",
    "Initial - August 14th 2022": "初始 - 2022 年 8 月 14 日",
    "Multiply EP production by 10 (multiplicative).": "将 EP 产量乘以 10（乘法）。",
    "Perpetual  Uranium Cell": "永久铀电池",
    "Plutonium Cell  cells last twice as long per level of upgrade (multiplicative).": "每个升级级别（乘法），钚电池 电池的持续时间增加一倍。",
    "Reflectors are automtically replaced after being destroyed if they are on a cool surface. The replacement part will cost 1.5 times the normal cost.": "如果反射器位于凉爽的表面上，它们会在被破坏后自动更换。更换零件的成本是正常成本的 1.5 倍。",
    "Reinforced Heat Exchangers": "加强型热交换器",
    "Uranium Cell  cells are automatically replaced when they become depleted. The replacement cell will cost 1.5 times the normal cost.": "铀电池 电池耗尽时会自动更换。更换电池的成本是正常成本的 1.5 倍。",
    "Basic Capacitor": "基本电容器",
    "Basic Coolant Cell": "基本冷却液电池",
    "Basic Heat Exchanger": "基本热交换器",
    "Basic Heat Inlet": "基本热入口",
    "Basic Heat Outlet": "基本热出口",
    "Basic Heat Vent": "基本散热孔",
    "Basic Neutron Reflector": "基本中子反射器",
    "Basic Particle Accelerator": "基本粒子加速器",
    "Basic Reactor Plating": "基础反应堆电镀",
    "but this device is actually powered by a hamster wheel. Mind blown!": "但这个设备实际上是由仓鼠轮驱动的。脑洞大开！",
    "Generates Exotic Particles based on heat passing through the accelerator (maximum 500M). If this part explodes it causes instant reactor meltdown. Holds a maximum of 1B heat. (It is strongly advised to supply heat directly from cells!)": "根据通过加速器的热量生成奇异粒子（最大 500M）。如果这部分爆炸，它会导致反应堆瞬间熔毁。最多可容纳 1B 热量。 （强烈建议直接从电池供热！）",
    "Instead of using a liquid to increase the thermal mass of the reactor, we opted to add metal plates.": "我们没有使用液体来增加反应器的热质量，而是选择添加金属板。",
    "It's just pipes filled with coolant.": "它只是装满冷却液的管道。",
    "Its like a heat exchanger but it has a constant access to chilled coolant.": "它就像一个热交换器，但它可以不断地获得冷却的冷却剂。",
    "Its like a heat exchanger but it has a constant access to hot coolant.": "它就像一个热交换器，但它可以不断地使用热冷却剂。",
    "Sheets of metal used to store energy.": "用于储存功率的金属片。",
    "This is literally procrastination of heat management.": "这实际上是对热量管理的拖延。",
    "This mesh based reflection surface reflects neutrons back in the 4 cardinal directions.": "这种基于网格的反射表面将中子反射回 4 个基本方向。",
    "We produce suspicious particles that an anonymous source trades for technology by using thermal energy to accelerate individual atoms.": "我们产生可疑粒子，匿名来源通过使用热能加速单个原子来换取技术。",
    "Advanced Heat Exchanger": "先进的热交换器",
    "Advanced Heat Inlet": "高级热入口",
    "Advanced Heat Outlet": "先进的热出口",
    "Advanced Heat Vent": "先进的散热孔",
    "Plutonium Cell": "钚电池",
    "The most common isotope of Uranium, Uranium-238, is not useable as nuclear fuel until it is given an extra neutron AND beta decay occurs TWICE forming plutionium-239": "铀最常见的同位素 铀-238 不能用作核燃料，直到它被给予额外的中子并且 β 衰变发生两次形成钚 239",
    "Put a Heat Vent next to a power Cell": "在电池旁边放一个散热孔",
    "Purchase a Dual power Cell": "购买1个双电源电池",
    "Purchase an Upgrade": "购买1个升级",
    "Have at least 10 active power Cells in your reactor": "在你的反应堆中至少有 10 个激活的电池",
    "Advanced Coolant Cell": "高级冷却液电池",
    "Advanced Neutron Reflector": "高级中子反射器",
    "Purchase a Perpetual power Cell upgrade": "购买永久功率电池升级",
    "Advanced Capacitor": "高级电容器",
    "Advanced Reactor Plating": "高级反应堆电镀",
    "Increase your max power with a Capacitor": "使用电容器增加最大功率",
    "LOCKED": "未解锁",
    "More abundant in the earth's crust than uranium, but not economically more available, thorium produces less nuclear waste than uranium.": "地壳中的钍比铀更丰富，但在经济上并不更容易获得，钍产生的核废料比铀少。",
    "Generates Exotic Particles based on heat passing through the accelerator (maximum 200Qa). If this part explodes it causes instant reactor meltdown. Holds a maximum of 400Qa heat. (It is strongly advised to supply heat directly from cells!)": "根据通过加速器的热量生成奇异粒子（最大 200Qa）。 如果这部分爆炸，它会导致反应堆瞬间熔毁。 最多可容纳 400Qa 热量。 （强烈建议直接从电池供热！）",
    "Nefastium Cell": "氖电池",
    "Protium Cell": "氚电池",
    "Quad Dolorium Cell": "四重Dolorium电池",
    "Quad Nefastium Cell": "四重氖电池",
    "Quad Plutonium Cell": "四重钚电池",
    "Quad Protium Cell": "四重氕电池",
    "Quad Seaborgium Cell": "四重𬭳电池",
    "Quad Thorium Cell": "四钍电池",
    "Seaborgium Cell": "𬭳电池",
    "Super Capacitor": "超级电容",
    "Super Coolant Cell": "超级冷却液单元",
    "Super Heat Exchanger": "超级换热器",
    "Super Heat Inlet": "超热入口",
    "Super Heat Outlet": "超热出口",
    "Super Heat Vent": "超热通风口",
    "Super Neutron Reflector": "超级中子反射器",
    "Super Particle Accelerator": "超级粒子加速器",
    "Super Reactor Plating": "超级反应器电镀",
    "Takes 12.8T heat out of each adjacent component and puts it into the reactor each tick. Has a range of 2 squares.": "从每个相邻组件中取出 12.8T 热量，并在每个tick中将其放入反应器中。范围为 2 个方格。",
    "The engineers claim that it warps a 4th spatial dimension to actually be adjacent to a full row of components": "工程师声称它会扭曲第四空间维度，使其实际上与整排组件相邻",
    "The reflection surface on this contraption is made of near depleted nuclear fuel cells.": "这个装置上的反射面是由接近耗尽的核燃料电池制成的。",
    "Thermal Neutron Reflector": "热中子反射器",
    "Thermionic Coolant Cell": "热离子冷却液池",
    "This device requires more power than a single hamster wheel, but two hamster wheels would look ridiculus.": "这个装置比一个仓鼠轮需要更多的动力，但是两个仓鼠轮看起来很可笑。",
    "This extremely volatile synthetic substance is an early development that appears tro violate conservastion of mass and energy.": "这种极易挥发的合成物质是一种早期发展，似乎违反了质量和能量守恒。",
    "Thorium Cell": "钍电池",
    "Ultimate Capacitor": "终极电容器",
    "Ultimate Coolant Cell": "终极冷却液单元",
    "Ultimate Heat Exchanger": "终极热交换器",
    "Ultimate Heat Inlet": "终极热入口",
    "Ultimate Heat Outlet": "终极热出口",
    "Ultimate Heat Vent": "终极散热孔",
    "Ultimate Neutron Reflector": "终极中子反射器",
    "Ultimate Reactor Plating": "终极反应堆电镀",
    "Wonderous Capacitor": "奇妙的电容器",
    "Wonderous Coolant Cell": "奇妙的冷却液电池",
    "Wonderous Heat Exchanger": "奇妙的热交换器",
    "Wonderous Heat Inlet": "奇妙的热入口",
    "Wonderous Heat Outlet": "奇妙的热出口",
    "Wonderous Heat Vent": "奇妙的散热孔",
    "Wonderous Neutron Reflector": "奇妙的中子反射器",
    "Wonderous Reactor Plating": "奇妙的反应器电镀",
    "You can extually feel the warping of space in the presence of this device.": "在此设备的存在下，您可以真正感受到空间的扭曲。",
    "A fair trade I'd say.": "我想说的是公平交易。",
    "A synthetic radioactive metal usually used excluseively for research. A game developer would be wrong to represent it as nuclear fuel.": "一种合成放射性金属，通常专门用于研究。游戏开发商将其表示为核燃料是错误的。",
    "A synthetic substance formed exclusively from green plant matter.": "一种完全由绿色植物物质形成的合成物质。",
    "Advanced Particle Accelerator": "高级粒子加速器",
    "All objectives completed!": "所有目标完成！",
    "Attempts to balance the heat between itself, adjacent components and its entire row by percentage. Transfers up to 12.8T heat per tick for each adjacent component. Holds up to 160T heat.": "尝试按百分比平衡其自身、相邻组件及其整行之间的热量。为每个相邻组件每滴答传递高达 12.8 吨的热量。可容纳高达 160T 的热量。",
    "Being 100% honest, you're paying too much for this. You can get the same capacitor for 1/100th of the price and the metal casing doesn't justify the cost.": "100% 诚实，你为此付出了太多。您可以以 1/100 的价格获得相同的电容器，而金属外壳并不能证明成本合理。",
    "by ingoring safety standards we can store even more energy AND save a little cost by not cooling the power output!": "通过符合安全标准，我们可以存储更多的能量并通过不冷却功率输出节省一点成本！",
    "Charged Reactor Plating": "带电反应器电镀",
    "Chlorophymium Cell": "绿藻电池",
    "Dolorium Cell": "Dolorium 电池",
    "Dual Dolorium Cell": "双重Dolorium电池",
    "Dual Nefastium Cell": "双重氖电池",
    "Dual Plutonium Cell": "双重钚电池",
    "Dual Protium Cell": "双重氕电池",
    "Dual Seaborgium Cell": "双重𬭳电池",
    "Dual Thorium Cell": "双重钍电池",
    "Every single person who has worked with nefastium has died of a tragic unrelated accident within a year.": "每个与nefastium合作过的人都在一年内死于一场无关紧要的悲惨事故。",
    "Extreme Capacitor": "极限电容",
    "Extreme Heat Exchanger": "极端热交换器",
    "Extreme Heat Inlet": "极热入口",
    "Extreme Heat Outlet": "极热出口",
    "Extreme Vent": "极端通风口",
    "For some reason the mere presence of dolorium causes severe emotional pain.": "出于某种原因，仅仅存在 dolorium 就会导致严重的情绪痛苦。",
    "Generates Exotic Particles based on heat passing through the accelerator (maximum 10T). If this part explodes it causes instant reactor meltdown. Holds a maximum of 20T heat. (It is strongly advised to supply heat directly from cells!)": "根据通过加速器的热量生成奇异粒子（最大 10T）。如果这部分爆炸，它会导致反应堆瞬间熔毁。最多可容纳 20T 热量。 （强烈建议直接从电池供热！）",
    "Generate at least 200 power per tick": "每tick至少产生 200 能量",
    "Purchase one Improved Chronometers upgrade": "购买一项改进的计时器升级",
    "Auto-sell at least 500 power per tick": "自动售出至少 500 能量/tick",
    "Generate at least 500 power per tick": "每tick产生至少 500 能量",
    "Have 5 different kinds of components in your reactor": "反应堆中有 5 种不同的组件",
    "Have at least 10 Capacitors in your reactor": "反应堆中至少有 10 个电容器",
    "Upgrade Potent Uranium Cell to level 3 or higher": "将强效铀电池升级到 3 级或更高",
    "Have at least 5 active Quad Plutonium Cells in your reactor": "在你的反应堆中至少有 5 个活跃的四重钚电池",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Made Buttons darker for readability.": "使按钮更暗以提高可读性。",
    "Made the tooltip box larger.": "使工具提示框变大。",
    "Moved the pause button.": "移动了暂停按钮。",
    "Heavily boosted heat capacities of particle accelerators (2x max throughput)": "粒子加速器的热容量大大提高（最大吞吐量的 2 倍）",
    "Enhanced Acceleration": "增强加速",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    't': 't',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t\t\t\t\t": "\t\t\t\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Exotic Particles": "奇异粒子",
    "Reduce your Current Heat to ": "将您当前的热量减少到 ",
    "Cost:": "成本：",
    "Increases maximum heat of the reactor by ": "将反应堆的最大热量增加 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Rebooting the reactor will remove all parts, regular upgrades and money. Only your current experimental upgrades and EP will stay with you.": "重新启动反应堆将移除所有部件、定期升级和金钱。 只有您当前的实验性升级和 EP 将与您同在。",
    "All of the above applies, however this will undo all your experiment upgrades and refund all your Exotic Particles.": "以上所有内容均适用，但这将撤消您的所有实验升级并退还您所有的异域粒子。",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    " heat is taken out of the reactor and put into each adjacent component.": " 热量从反应器中取出并放入每个相邻的组件中。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)K EP$/,
    /^([\d\.]+)T$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^For each adjacent component (.+) is taken out of the reactor and put into the adjacent component. Has a range of 2 squares.$/, '对于每个相邻组件，从反应器中取出 $1 并放入相邻组件中。范围为 2 个方格。'],
    [/^Acts as (.+) Dolorium Cell cells. Produces (.+) power and (.+) heat per tick.$/, '充当 $1 Dolorium电池 电池。每tick产生 $2 的功率和 $3 的热量。'],
    [/^Acts as (.+) Nefastium Cell cells. Produces (.+) power and (.+) heat per tick.$/, '充当 $1 氖电池 电池。每tick产生 $2 的功率和 $3 的热量。'],
    [/^Acts as (.+) Seaborgium Cell cells. Produces (.+) power and (.+) heat per tick.$/, '充当 $1 𬭳电池 电池。每tick产生 $2 的功率和 $3 的热量。'],
    [/^Acts as (.+) Thorium Cell cells. Produces (.+) power and (.+) heat per tick.$/, '充当 $1 钍电池 电池。每tick产生 $2 的功率和 $3 的热量。'],
    [/^Acts as (.+) Plutonium Cell cells. Produces (.+) power and (.+) heat per tick.$/, '充当 $1 钚电池 电池。每tick产生 $2 的功率和 $3 的热量。'],
    [/^Acts as (.+) Protium Cell cells. Produces (.+) power and (.+) heat per tick. After being fully depleted, protium cells permanently generate 10\% more power per depleted cell.$/, '充当 $1 氕电池 电池。每tick产生 $2 的功率和 $3 氕电池每耗尽一个电池就会永久产生 10% 以上的功率。'],
    [/^Produces (.+) power and (.+) heat per tick. Lasts for (.+) ticks. Produces its peak power at noon and its minimum at midnight.$/, '每tick产生 $1 功率和 $2 热量。持续 $3 tick。在中午产生峰值功率，在午夜产生最小功率。'],
    [/^Produces (.+) power and (.+) heat per tick. Lasts for (.+) ticks. After being fully depleted, protium cells permanently generate 10% more power per depleted cell.$/, '每tick产生 $1 的功率和 $2 的热量。持续 $3 tick。在完全耗尽后，氕电池每耗尽一个电池就会永久产生 10% 以上的功率。'],
    [/^Holds (.+) heat before being destroyed.$/, '在被破坏之前保持 $1 热量。'],
    [/^Holds (.+) heat before being destroyed. 50\% of the heat added to this part is instantly converted to power and added to the generator.$/, '在被摧毁前拥有 $1 热量。 50\% 添加到这部分的热量会立即转化为功率并添加到发电机中。'],
    [/^Increases maximum heat and power of the reactor by (.+).$/, '将反应堆的最大热量和功率提高 $1。'],
    [/^Increases adjacent cell power output by (.+)\% and heat output by 50\% for for (.+) total pulses.$/, '对于 $2 总脉冲，将相邻单元的功率输出提高 $1\% 并且热量输出 50\%。'],
    [/^Increases adjacent cell power output by (.+)\% for (.+) total pulses.$/, '对于 $2 总脉冲，将相邻单元的功率输出提高 $1\%。'],
    [/^Produces (.+) power and (.+) heat per tick. Lasts for (.+) ticks.$/, '每tick产生 $1 功率和 $2 热量。 持续 $3 tick。'],
    [/^Increases the maximum power of the reactor by (.+). Holds a maximum of (.+) heat.$/, '将反应堆的最大功率提高 $1. 最多可容纳 $2 热量。'],
    [/^Increases the maximum power of the reactor by (.+). Holds a maximum of (.+) heat. Heat is added to each unit equal to 50% of the power automatically sold by it.$/, '将反应堆的最大功率提高 $1. 最多可容纳 $2 热量。热量被添加到每个单元，相当于它自动售出的功率的 50%。'],
    [/^Acts as (.+) Uranium Cell cells. Produces (.+) power and (.+) heat per tick.$/, '充当 $1 个铀电池单元。 每tick产生 $2 功率和 $3 热量。'],
    [/^Takes (.+) heat out of each adjacent component and puts it into the reactor each tick.$/, '从每个相邻组件中取出 $1 热量，并在每个tick中将其放入反应器中。'],
    [/^Lowers heat of itself by (.+) per tick. Holds a maximum of (.+) heat.$/, '每tick降低自身的热量 $1. 最多可容纳 $2 热量。'],
    [/^Lowers heat of itself by (.+) per tick. Holds a maximum of (.+) heat. Must consume power from the reactor at a rate of 100% of the heat removed from itself.$/, '每tick降低自身的热量 $1. 最多可容纳 $2 热量。必须以 100% 的速度从反应堆消耗自身的热量。'],
    [/^Attempts to balance the heat between itself and adjacent components by percentage. Transfers up to (.+) heat per tick for each adjacent component. Holds up to (.+) heat.$/, '尝试按百分比平衡自身和相邻组件之间的热量。每个相邻组件每tick最多可传递 $1 热量。可容纳高达 $2 的热量。'],
    [/^Attempts to balance the heat between itself and adjacent components by percentage. Transfers up to (.+) heat per tick for each adjacent component. Holds up to (.+) heat.$/, '尝试按百分比平衡自身和相邻组件之间的热量。 为每个相邻组件每滴答传递高达 $1 的热量。 可容纳高达 $2 的热量。'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到功率增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);