/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "Improvement:": "改进：",
    "New Features:": "新功能：",
    "Options": "选项",
    "Patch Notes": "更新日志",
    "Upgrades": "升级",
    "You can no longer place locked components^2.": "您不能再放置锁定的组件^2。",
    "Experimental Upgrades": "实验性升级",
    "Experiments": "实验",
    "Export save": "导出存档",
    "Faster repaint time by layering frequently updated ui (Improve fps/lag)": "通过对频繁更新的 ui 进行分层来加快重绘时间（提高 fps/lag）",
    "Faster tick timing (faster loading after offline)": "更快的滴答时间（离线后加载更快）",
    "Features:": "特征：",
    "Fixed an issue with game loop firing too often": "修复了游戏循环触发过于频繁的问题",
    "Fixed sell costs for some components": "某些组件的固定出售成本",
    "Fixed support for larger touch devices to allow for selling, etc": "修复了对更大触摸设备的支持以允许出售等",
    "Fixes extreme plating adding to max power despite not being bought yet": "尽管尚未购买，但修复了极端电镀以增加最大功率",
    "Fixes Heat Control Operator adding heat": "修复了热量控制操作员添加热量的问题",
    "Fixes heat outlet heat distribution bug with multi-tier setup": "修复了多层设置的热出口热量分布错误",
    "Fixes reflector ui load bug": "修复反射器 ui 加载错误",
    "Greatly improve performance": "大大提高性能",
    "Heat": "热量",
    "Heavily optimized the protium code that I ruined.": "对我破坏的 protium 代码进行了大量优化。",
    "Help": "帮助",
    "Hold keys in bracket and click to use the macro": "按住括号中的键并单击以使用宏",
    "Implemented Chlorophymium.": "实施了绿藻。",
    "Import save": "进口锯",
    "Changes": "变化",
    "Changes:": "变化：",
    "Checkered fill (ctrl+alt+shift)": "方格填充（ctrl+alt+shift）",
    "Click to Select": "点击选择",
    "Click to Upgrade": "点击升级",
    "Column (alt)": "列（alt）",
    "Components": "组件",
    "Coolant Innovation.": "冷却液创新。",
    "Current": "当前的",
    "Disable Auto Buy": "禁用自动购买",
    "Disable Auto Sell": "禁用自动出售",
    "Disable Heat Controller": "禁用热控制器",
    "Disable Offline Tick": "禁用离线Tick",
    "Disable Speed Hack": "禁用 Speed Hack",
    "Don't filter by part (shift)": "不要按零件过滤（shift）",
    "Download save": "下载保存",
    "Enable Google Drive Online Save": "启用 谷歌在线云盘 保存",
    "Enable Heat Controller": "启用热控制器",
    "Enable Local Save Only": "仅启用本地保存",
    "Enable Speed Hack": "启用速度破解",
    "Cancel": "取消",
    "A modification of": "修改",
    "A reset button!": "一个重置按钮！",
    "About": "关于",
    "Added individual experimental Particle Accelerator upgrades": "添加了单个实验性粒子加速器升级",
    "Added mitochdonrium.": "添加了线粒体。",
    "Added Objectives": "添加的目标",
    "Added patch notes": "添加了补丁说明",
    "Additional hotkeys/macro:": "其他热键/宏：",
    "Additions:": "补充：",
    "All accelerators no hold a max of 100 heat to prevent abuse of higher tiers.": "所有加速器都不能容纳最多 100 个热量，以防止滥用更高等级。",
    "Approximate EP per tick display.": "每个刻度显示的近似 EP。",
    "Back to Reactor": "回到反应堆",
    "Bang For Your Buck.": "全力以赴。",
    "Based on": "基于",
    "Basic Overview": "基本概述",
    "Buch": "布赫",
    "Bug fixes:": "Bug修复：",
    "Bug Fixes:": "Bug修复：",
    "Vent and Plating boosts for components multiply together instead of adding.": "排气和电镀促进组件相乘而不是相加。",
    "The game is immediately paused on loading or importing.": "游戏在加载或导入时立即暂停。",
    "Tick catchup": "Tick catchup",
    "Tile queue now buys as many as possible per tick": "瓷砖队列现在每次购买尽可能多",
    "UI based on": "用户界面基于",
    "Unpause": "取消暂停",
    "Upgrade tick catchup to offline ticks!": "将 tick catchup 升级为 离线tick！",
    "Usage": "用法",
    "Increase utility prices.": "提高公用事业价格。",
    "last tick)": "上一 tick）",
    "Left+right click triggering double click function and deleting tiles": "左键+右键触发双击功能并删除图块",
    "Less cpu usage when not on reactor tile panel": "不在反应器瓷砖面板上时减少 cpu 使用率",
    "Less lag spike for UI, tooltip": "UI、工具提示的层数减少",
    "Made help helpful.": "使帮助有所帮助。",
    "Make sure background get updated when placing plating so it doesn't get stuck on red": "确保在放置电镀时背景得到更新，这样它就不会卡在红色上",
    "Many upgrades now have a second tier.": "许多升级现在都有第二层。",
    "Moved the Coolant Innovation upgrade.": "移动冷却液创新升级。",
    "Multiple Exotic Particles gained when over 100% chance": "超过 100% 的几率获得多个奇异粒子",
    "New upgrade which prevents outlets from outputting more than what the vent can handle": "新升级可防止出口的输出超过通风口的处理能力",
    "Objective": "目标",
    "Offline Tick": "离线Tick",
    "Particle accelerators now have a standard upgrade.": "粒子加速器现在有一个标准升级。",
    "Parts": "零件",
    "Pause": "暂停",
    "per tick)": "每tick）",
    "Percentage bar and overheating redness are now updated in steps (reduce repainting)": "百分比条和过热发红现在分步更新（减少重绘）",
    "Place your first component in the reactor": "将您的第一个组件放入反应器中",
    "Platings (and possibly other things) now give 100% of their cost back when sold": "镀层（可能还有其他东西）现在在售出时返还 100% 的成本",
    "Power": "电力",
    "Reactor": "反应堆",
    "Reactor Incremental": "反应堆增量",
    "Reactor Knockoff": "反应堆仿制品",
    "Reactor meltdowns no longer instantly save the game.": "反应堆熔毁不再立即拯救游戏。",
    "Reboot and refund": "重启和退款",
    "Reboot for": "重新启动",
    "Reflectors now start with a base % greater than 0": "反射器现在以大于 0 的基本百分比开始",
    "Removed old Particle Accelerator upgrades": "移除旧的粒子加速器升级",
    "Reorganized upgrades.": "重组升级。",
    "Replaced every texture with similar ones of my own.": "用我自己的类似纹理替换了每个纹理。",
    "Replacing now works with same category parts, eg: downgrading, switching cell type": "替换现在适用于相同类别的部件，例如：降级、切换单元类型",
    "Replacing tiles is now faster": "更换瓷砖现在更快",
    "Replacing tiles with another now reimburse the amount for the part": "现在用另一个替换瓷砖可以补偿该部分的金额",
    "Reset game": "重置游戏",
    "Retexture:": "重新构造：",
    "Right click no longer buy stuff": "右键不再买东西",
    "Row (ctrl)": "行 (ctrl)",
    "Save data exporting and importing": "保存数据导出和导入",
    "Save game": "保存游戏",
    "Sci-fi User Interface Elements": "科幻用户界面元素",
    "See Patch Notes": "查看补丁说明",
    "Sell": "卖",
    "Shift/Double click now works on empty tiles": "Shift/双击现在适用于空瓷砖",
    "Signific code changes that shouldn't (but may) affect gameplay": "不应（但可能）影响游戏玩法的重大代码更改",
    "Spacing options (number)": "间距选项（数量）",
    "Speed Hack": "极速破解",
    "Speed hack toggle, throw more stuff into their own layer and thus reduce paint time (at the cost of memory)": "Speed hack切换，将更多的东西扔到自己的图层中，从而减少绘制时间（以内存为代价）",
    "Stats": "状态",
    "Styling fixes to \"pages\"": "对“页面”的样式修复",
    "% of max)\n\t\t": "% 最大)\n\t\t",
    "Dual Uranium Cell": "双铀电池",
    "Enable Auto Buy": "启用自动购买",
    "Enable Auto Sell": "启用自动出售",
    "Sell all your power by clicking \"Sell\"": "通过点击“出售”出售你所有的电力",
    "Uranium Cell": "铀电池",
    "% per tick (": "% 每 tick (",
    "), Improved Heatsinks level (S), Active Venting level (A)\n\t\t\t\t\t\t\tVentillation:\tV * (1 + A * C": "), 改进的散热器级别 (S), 主动通风级别 (A)\n\t\t\t\t\t\t\t通风：\tV * (1 + A * C",
    "), Sum of all plating tiers (P": "), 所有电镀层的总和 (P",
    "), Reinforced Heat Exchnagers level (R), Active Exchnagers level (A)\n\t\t\t\t\t\t\tTransfer Rate:\tT * (1 + A * C": "), 强化换热器等级 (R), 主动换热器等级 (A)\n\t\t\t\t\t\t\t 传输率：\tT * (1 + A * C",
    "/ 200)\n\t\t\t\t\t\t\tHeat Capacity:\tC * (1 + A * C": "/ 200)\n\t\t\t\t\t\t\t热容量：\tC * (1 + A * C",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Exotic Particles": "奇异粒子",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);